version: "3"
networks:
    db_net:
        driver: bridge

services:
    db:
        image: postgres:10  
        hostname: db                                                   
        container_name: db                                            
        environment:                                                            
            - POSTGRES_USER=user                                                
            - POSTGRES_PASSWORD=pass                                            
            - POSTGRES_DB=db
        networks:
            - db_net
        ports:
            - 5432:5432

    api:                                                                        
        build: .                                                                
        depends_on:                                                             
            - db                                                                
        networks:                                                               
            - db_net
